//! HDFC Bank savings-account statement adapter.
//!
//! ## Row anatomy
//!
//! Each transaction in the extracted text begins with `DD/MM/YY` (two-digit
//! year), followed by narration, reference number, value date, amount, and
//! closing balance:
//!
//! ```text
//! 01/05/26 UPI-MAHAVIR SWEETS AND F-GPAY-1219049458 0000648728252238 01/05/26 207.00 153,438.55
//! 04/05/26 UPI-CRED CLUB-CRED.CLUB@AXISB-UTIB000011 0000649003914140 04/05/26 21,447.00 128,491.51
//! ```
//!
//! The PDF has separate "Withdrawal Amt." and "Deposit Amt." columns but
//! pdfium's text extraction collapses the blank column to whitespace, so we
//! cannot tell direction from token position. Instead we **infer direction
//! from the balance delta** — debit if balance fell, credit if balance rose,
//! relative to the previous row's balance. Opening balance is parsed from
//! the statement header (`Opening Balance ... NN,NNN.NN`) and used to seed
//! the very first row.
//!
//! ## Wrap-line handling
//!
//! Narrations sometimes wrap to a second line. The row anchor regex matches
//! only lines starting with `DD/MM/YY`, so wrap continuations are absorbed
//! into the previous row until the next anchor or a hard break (empty line,
//! `Page N of M`, or a known section header) interrupts.

use crate::adapter::{BankAdapter, ParseError};
use crate::extracted::ExtractedPdf;
use crate::raw_txn::RawTransaction;
use fm_core::Amount;
use regex::Regex;
use rust_decimal::Decimal;
use std::sync::OnceLock;

pub struct HdfcSavingsAdapter;

const ADAPTER_ID: &str = "hdfc-savings";
const ADAPTER_VERSION: &str = "1.0.0";

impl HdfcSavingsAdapter {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for HdfcSavingsAdapter {
    fn default() -> Self {
        Self::new()
    }
}

fn anchor_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| Regex::new(r"^(\d{2})/(\d{2})/(\d{2})\s+(.+)$").expect("static regex"))
}

fn trailing_amount_balance_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| Regex::new(r"([\d,]+\.\d{2})\s+([\d,]+\.\d{2})\s*$").expect("static regex"))
}

fn opening_balance_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        Regex::new(r"(?i)opening\s+balance[^\d]*([\d,]+\.\d{2})").expect("static regex")
    })
}

fn is_hard_break(line: &str) -> bool {
    let t = line.trim();
    if t.is_empty() {
        return true;
    }
    if t.starts_with("Page ") {
        return true;
    }
    let lower = t.to_lowercase();
    matches!(
        lower.as_str(),
        "statement summary"
            | "*closing balance*"
            | "**end of statement**"
            | "generated by"
            | "generated on"
    ) || lower.starts_with("*** end of statement")
        || lower.starts_with("statement summary")
}

impl BankAdapter for HdfcSavingsAdapter {
    fn id(&self) -> &'static str {
        ADAPTER_ID
    }

    fn version(&self) -> &'static str {
        ADAPTER_VERSION
    }

    fn detect(&self, extracted: &ExtractedPdf) -> bool {
        let name = extracted.source_file.to_lowercase();
        if name.contains("hdfc") && name.contains("savings") {
            return true;
        }
        extracted.pages.iter().any(|p| {
            let lower = p.text.to_lowercase();
            let is_hdfc = lower.contains("hdfc bank")
                || lower.contains("hdfc bank limited")
                || lower.contains("hdfcbank");
            let is_savings_statement = lower.contains("statement of account")
                || lower.contains("savings account")
                || (lower.contains("opening balance") && lower.contains("closing balance"));
            is_hdfc && is_savings_statement
        })
    }

    fn parse(
        &self,
        extracted: &ExtractedPdf,
        import_id: &str,
    ) -> Result<Vec<RawTransaction>, ParseError> {
        let mut out = Vec::new();
        let mut row_counter: u32 = 0;
        let parser_version = format!("{ADAPTER_ID}@{ADAPTER_VERSION}");

        // Seed running balance from header if available.
        let mut prev_balance: Option<Decimal> = find_opening_balance(extracted);

        for page in &extracted.pages {
            let lines: Vec<&str> = page.text.lines().collect();
            let mut i = 0;
            while i < lines.len() {
                let Some(caps) = anchor_re().captures(lines[i]) else {
                    i += 1;
                    continue;
                };

                let day: u32 = caps[1].parse().map_err(|_| {
                    ParseError::BadDate(format!("non-numeric day in: {}", lines[i]))
                })?;
                let month: u32 = caps[2].parse().map_err(|_| {
                    ParseError::BadDate(format!("non-numeric month in: {}", lines[i]))
                })?;
                let yr2: u32 = caps[3].parse().map_err(|_| {
                    ParseError::BadDate(format!("non-numeric year in: {}", lines[i]))
                })?;
                if !(1..=31).contains(&day) || !(1..=12).contains(&month) {
                    return Err(ParseError::BadDate(format!(
                        "out of range in: {}",
                        lines[i]
                    )));
                }
                let year = 2000 + yr2;

                let mut joined = caps[4].to_string();
                let mut j = i + 1;
                while j < lines.len()
                    && anchor_re().captures(lines[j]).is_none()
                    && !is_hard_break(lines[j])
                {
                    joined.push(' ');
                    joined.push_str(lines[j].trim());
                    j += 1;
                }
                let advance = j.max(i + 1);

                let Some(ab_caps) = trailing_amount_balance_re().captures(&joined) else {
                    i = advance;
                    continue;
                };
                let amount_token = ab_caps.get(1).unwrap().as_str();
                let balance_token = ab_caps.get(2).unwrap().as_str();
                let amount = Amount::parse_inr(amount_token)?.amount;
                let balance = Amount::parse_inr(balance_token)?.amount;

                let direction_credit = match prev_balance {
                    Some(prev) => balance.as_decimal() > prev,
                    None => false,
                };
                prev_balance = Some(balance.as_decimal());

                let desc_end = ab_caps.get(0).unwrap().start();
                let description = joined[..desc_end].trim().to_string();
                if description.is_empty() {
                    i = advance;
                    continue;
                }

                let txn_date = format!("{year:04}-{month:02}-{day:02}");
                let (debit, credit) = if direction_credit {
                    (None, Some(amount))
                } else {
                    (Some(amount), None)
                };

                row_counter += 1;
                out.push(RawTransaction {
                    import_id: import_id.to_string(),
                    source_file: extracted.source_file.clone(),
                    source_sha256: extracted.source_sha256.clone(),
                    source_page: page.page_number,
                    row_number: row_counter,
                    parser_version: parser_version.clone(),
                    parser_backend: extracted.backend,
                    txn_date,
                    description,
                    debit,
                    credit,
                    balance: Some(balance),
                });

                i = advance;
            }
        }

        Ok(out)
    }
}

fn find_opening_balance(extracted: &ExtractedPdf) -> Option<Decimal> {
    for p in &extracted.pages {
        if let Some(caps) = opening_balance_re().captures(&p.text) {
            if let Ok(parsed) = Amount::parse_inr(caps.get(1).unwrap().as_str()) {
                return Some(parsed.amount.as_decimal());
            }
        }
    }
    None
}
